import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { MainLayout } from "@/core/layouts/main-layout";
import { TweetList } from "@/features/tweet/components/tweet-list/TweetList";
import { CreateTweet } from "@/features/tweet/components/create-tweet/CreateTweet";
import { useSession } from "next-auth/react";
import { getAllTweets } from "@/features/tweet/services/server/get-all-tweets";
import { dbConnect } from "@/core/utils/db";
import { getServerSession } from "next-auth";
import { authOptions } from "../api/auth/[...nextauth]";
import LikeModel from "@/core/schemas/likes.schema";


export async function getServerSideProps(ctx) {
  await dbConnect();
  let tweets = await getAllTweets();
  const {user} = await getServerSession(ctx.req, ctx.res, authOptions);
  const likeIds = tweets.map((tweet) => tweet.id + user.id);
  const likes = await LikeModel.find({ likeId: { $in: likeIds } });
  let likedTweetIds = likes.map((like) => like.tweet.toString());
  likedTweetIds = new Set(likedTweetIds)
  tweets = tweets.map((tweet) =>({...tweet,isLiked:likedTweetIds.has(tweet.id.toString())}));
  return {
    props: {
      tweets: JSON.parse(JSON.stringify(tweets)),
    },
  };
}


function Page({ tweets }) {
  const { data, status } = useSession();
  console.log(status, data);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.home}>
        <div className="center-container">
          <div className="appbar">Home</div>
          <div className="content">
            <CreateTweet />
            <TweetList tweets={tweets} />
          </div>
        </div>
        <div className={styles.rightBar}></div>
      </div>
    </>
  );
}
Page.Layout = MainLayout;
export default Page;
