import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { MainLayout } from "@/core/layouts/main-layout";
import { CreateTweet } from "@/features/tweet/components/create-tweet/CreateTweet";
import { useSession } from "next-auth/react";
import { getServerSession } from "next-auth";
import { YouMayKnow } from "@/features/user/components/you-may-know/YouMayKnow";
import { TweetView } from "@/features/tweet/components/tweet-view/TweetView";
import { useAutoAnimate } from "@formkit/auto-animate/react";
import { useListState } from "@/shared/hooks/useListState";
import {
  getUser,
  getUsers,
} from "@/features/user/services/server/get-user.server";
import {
  getAllTweets,
  getFeed,
  getUserFeed,
} from "@/features/tweet/services/server/get-tweet.server";
import { dbConnect } from "@/core/utils/db";
import { createOptions } from "../api/auth/[...nextauth]";
import { useEffect, useReducer, useRef, useState } from "react";
import useIntersectionObserver from "@/shared/hooks/useIntersectionObserver";
import { useOnScreen } from "@/shared/hooks/useOnScreen";
import { useCustomState } from "@/shared/hooks/useCustomState";
import useSwr from "swr";
import { fetcher } from "@/shared/utils/fetcher";
import axios from "axios";
import { trusted } from "mongoose";
import { MessageProvider } from "@/core/Providers/MessageProvider";

export async function getServerSideProps(ctx) {
  await dbConnect();
  const { user } = await getServerSession(
    ctx.req,
    ctx.res,
    createOptions(ctx.req)
  );
  const tweetsPromise = getUserFeed({
    userId: user.id,
    pageIndex: 1,
    pageSize: 10,
  });
  const usersPromise = getUsers();
  let [tweetsPage, users] = await Promise.all([tweetsPromise, usersPromise]);
  return {
    props: JSON.parse(
      JSON.stringify({
        tweetsPage: tweetsPage,
        users: users.filter((u) => u.id != user.id),
      })
    ),
  };
}

function Page({ tweetsPage, users }) {
  const tweetList = useListState(tweetsPage.data);
  const loaderRef = useRef();
  const isLoaderOnScreen = !!useIntersectionObserver(loaderRef,{})?.isIntersecting;
  const pageIndex = useCustomState(2);
  const isLastPage = useCustomState(false);
  useEffect(() => {
    if (isLoaderOnScreen && !isLastPage.value) {
      const fetchNewPost = async () => {
        try {
          const { data: newPage } = await axios.get(
            `/api/tweet/?pageIndex=${pageIndex.value}&pageSize=${tweetsPage.pageSize}`
          );
          if (newPage?.data?.length === 0) {
            isLastPage.set(true);
          } else tweetList.set((state) => [...state, ...newPage?.data]);
          pageIndex.set((v) => v + 1);
        } catch (err) {}
      };
      fetchNewPost();
    }
  }, [isLoaderOnScreen]);

  const [parent, _] = useAutoAnimate();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout onNewTweet={tweetList.add}>
        <div className={styles.home}>
          <div className="center-container">
            <div className="appbar">Home</div>
            <div className="content">
              <CreateTweet
                onComplete={(tweet) => {
                  if (tweet) tweetList.add(tweet);
                }}
              />
              <div ref={parent}>
                {tweetList.value.map((tweet) => (
                  <TweetView
                    tweet={tweet}
                    key={tweet.id}
                    onDelete={tweetList.remove}
                  />
                ))}
                {isLastPage.value ? (
                  <div className="w-full center" style={{padding:'1rem',color:'var(--grey)'}}>no more tweets</div>
                ) : (
                  <div
                    className="w-full center"
                    style={{
                      fontSize: "2rem",
                      padding: "1rem",
                      color: "var(--primary-color)",
                    }}
                  >
                    <div ref={loaderRef} className="loader"></div>
                  </div>
                )}
              </div>
            </div>
          </div>
          <div className={styles.rightBar}>
            <YouMayKnow users={users} />
          </div>
        </div>
      </MainLayout>
    </>
  );
}
export default Page;
