import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { MainLayout } from "@/core/layouts/main-layout";
import { TweetList } from "@/features/tweet/components/tweet-list/TweetList";
import { AuthCard } from "@/features/auth/components/auth-card/AuthCard";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]";
import { useSession } from "next-auth/react";
import { useRouter } from "next/router";


export async function getServerSideProps(context) {
  const session = await getServerSession(context.req,context.res,authOptions)
  if (session) {
    return {
      redirect: {
        destination: '/home',
        permanent: false,
      },
    }
  }
  return {
    props: {},
  }
}

function Page({}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.home}>
        <div className="center-container">
          <div className="appbar">Explore</div>
          <TweetList />
        </div>
        <div className={styles.rightBar}>
          <AuthCard />
        </div>
      </div>
    </>
  );
}

Page.Layout = MainLayout;
export default Page;

